### ISSUE TITLE
export is a keyword already. 

### ISSUE THREAD

**Issue by Vectormike** [sheghun/paystack2#1]
https://github.com/sheghun/paystack2/blob/02e9ac6130aacdd6c861661311475d0e5fdc0132/resources/transaction.ts#L99

**Comment by solomon-os** [comment]
It still works though.
But if you want you can change the function

**Comment by Vectormike** [comment]
Alright, but egungun be kiaful 😒

**Comment by solomon-os** [comment]
😂, Make egungun rest abeg
